### ISSUE TITLE
Is this still operational?

### ISSUE THREAD

**Issue by akarshghale** [Shkaolin/BERTopic-as-service#24]
Hi,

I would like to know whether this repo is still operational. 

Also, is this docker image packaged with Bertopic as i think or it's something else? 

If it is then is there a tutorial on how to use Bertopic within it?

**Comment by SergeyShk** [comment]
Hello. Yes, it is. If you say about this (_docker pull ghcr.io/shkaolin/bertopic-as-service:latest_), then it is an image of the latest version of this service to use it directly without building manually. You can see how to use BERTopic actually in corresponding repo - https://github.com/MaartenGr/BERTopic

**Comment by akarshghale** [comment]
Hi, i am referring to the API documentation for this. 

Where is the information to see how to make POST request?
